"""
app/data_store.py
-------------------
Loads the read-only catalog (cities, hotels, room types, rooms,
restaurants, tables, dishes, activities, customers) from the CSV files
generated by the `generator/` script, and implements the `BookingStore`:
the in-memory + SQLite-backed collection of bookings, with the overlap /
capacity checks used by both the availability and the booking-creation
endpoints.

Visibility rule (see README.md): whenever bookings are read (for listing,
availability checks, or overlap validation), the set considered is always
"seed bookings" + "bookings created by the requesting IP" — never bookings
created by a different IP. This is what keeps workshop attendees from
colliding with each other.
"""
from __future__ import annotations

import csv
import itertools
import threading
from datetime import date, datetime
from pathlib import Path
from typing import Optional

from . import config, db

BLOCKING_STATUSES = {"pending", "confirmed", "completed"}


# ---------------------------------------------------------------------------
# CSV parsing helpers
# ---------------------------------------------------------------------------
def _read_csv_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(
            f"Seed data file not found: {path}. Did you set DATA_DIR correctly, "
            f"and does it contain the CSVs produced by the generator?"
        )
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _b(v: str) -> bool:
    return str(v).strip().lower() in ("true", "1", "yes")


def _lst(v: str) -> list[str]:
    v = (v or "").strip()
    return v.split(";") if v else []


def _i(v, default=None):
    v = v.strip() if isinstance(v, str) else v
    if v in (None, ""):
        return default
    return int(float(v))


def _f(v, default=None):
    v = v.strip() if isinstance(v, str) else v
    if v in (None, ""):
        return default
    return float(v)


def _d(v) -> date:
    return datetime.strptime(v.strip(), "%Y-%m-%d").date()


def _dt(v) -> datetime:
    return datetime.strptime(v.strip(), "%Y-%m-%d %H:%M:%S")


# ---------------------------------------------------------------------------
# Catalog loaders
# ---------------------------------------------------------------------------
def _load_cities(path: Path) -> list[dict]:
    return [{"city_id": _i(r["city_id"]), "name": r["name"]} for r in _read_csv_rows(path)]


def _load_hotels(path: Path) -> list[dict]:
    out = []
    for r in _read_csv_rows(path):
        out.append({
            "hotel_id": _i(r["hotel_id"]), "name": r["name"], "description": r["description"],
            "category": _i(r["category"]), "type": r["type"], "city": r["city"],
            "check_in_time": r["check_in_time"], "check_out_time": r["check_out_time"],
            "reception_24h": _b(r["reception_24h"]), "services": _lst(r["services"]),
            "pet_friendly": _b(r["pet_friendly"]), "accessible": _b(r["accessible"]),
            "rating": _f(r["rating"]), "review_count": _i(r["review_count"]),
            "price_range": r["price_range"],
        })
    return out


def _load_room_types(path: Path) -> list[dict]:
    out = []
    for r in _read_csv_rows(path):
        out.append({
            "room_type_id": _i(r["room_type_id"]), "hotel_id": _i(r["hotel_id"]),
            "name": r["name"], "description": r["description"],
            "max_adults": _i(r["max_adults"]), "max_children": _i(r["max_children"]),
            "bed_configuration": r["bed_configuration"], "size_m2": _i(r["size_m2"]),
            "bathroom_type": r["bathroom_type"], "services": _lst(r["services"]),
            "accessible": _b(r["accessible"]), "base_price_per_night": _f(r["base_price_per_night"]),
            "breakfast_included": _b(r["breakfast_included"]),
            "cancellation_policy": r["cancellation_policy"],
        })
    return out


def _load_rooms(path: Path) -> list[dict]:
    out = []
    for r in _read_csv_rows(path):
        out.append({
            "room_id": _i(r["room_id"]), "hotel_id": _i(r["hotel_id"]),
            "room_type_id": _i(r["room_type_id"]), "room_number": r["room_number"],
            "floor": _i(r["floor"]), "status": r["status"], "notes": r["notes"],
        })
    return out


def _load_restaurants(path: Path) -> list[dict]:
    out = []
    for r in _read_csv_rows(path):
        out.append({
            "restaurant_id": _i(r["restaurant_id"]), "name": r["name"], "description": r["description"],
            "cuisine_types": _lst(r["cuisine_types"]), "city": r["city"],
            "opening_hours": r["opening_hours"], "price_range": r["price_range"],
            "rating": _f(r["rating"]), "review_count": _i(r["review_count"]),
            "services": _lst(r["services"]), "accessible": _b(r["accessible"]),
            "pet_friendly": _b(r["pet_friendly"]), "dress_code": r["dress_code"],
            "max_capacity": _i(r["max_capacity"]),
        })
    return out


def _load_tables(path: Path) -> list[dict]:
    out = []
    for r in _read_csv_rows(path):
        out.append({
            "table_id": _i(r["table_id"]), "restaurant_id": _i(r["restaurant_id"]),
            "table_number": _i(r["table_number"]), "capacity": _i(r["capacity"]),
            "location": r["location"], "accessible": _b(r["accessible"]), "status": r["status"],
        })
    return out


def _load_dishes(path: Path) -> list[dict]:
    out = []
    for r in _read_csv_rows(path):
        out.append({
            "dish_id": _i(r["dish_id"]), "restaurant_id": _i(r["restaurant_id"]),
            "name": r["name"], "description": r["description"], "category": r["category"],
            "price": _f(r["price"]), "currency": r["currency"],
            "ingredients": _lst(r["ingredients"]), "allergens": _lst(r["allergens"]),
            "dietary_tags": _lst(r["dietary_tags"]), "spicy_level": _i(r["spicy_level"]),
            "calories": _i(r["calories"]), "available": _b(r["available"]),
        })
    return out


def _load_activities(path: Path) -> list[dict]:
    out = []
    for r in _read_csv_rows(path):
        out.append({
            "activity_id": _i(r["activity_id"]), "name": r["name"], "description": r["description"],
            "activity_type": r["activity_type"], "category": r["category"], "city": r["city"],
            "opening_hours": r["opening_hours"], "duration_minutes": _i(r["duration_minutes"]),
            "min_age": _i(r["min_age"]), "max_age": _i(r["max_age"], default=None),
            "accessible": _b(r["accessible"]), "indoor_outdoor": r["indoor_outdoor"],
            "max_capacity": _i(r["max_capacity"]), "rating": _f(r["rating"]),
            "review_count": _i(r["review_count"]), "services": _lst(r["services"]),
            "price": _f(r["price"]),
        })
    return out


def _load_customers(path: Path) -> list[dict]:
    out = []
    for r in _read_csv_rows(path):
        out.append({
            "customer_id": _i(r["customer_id"]), "first_name": r["first_name"],
            "last_name": r["last_name"], "date_of_birth": _d(r["date_of_birth"]),
        })
    return out


def _load_seed_bookings(path: Path) -> list[dict]:
    out = []
    for r in _read_csv_rows(path):
        out.append({
            "booking_id": _i(r["booking_id"]), "booking_reference": r["booking_reference"],
            "customer_id": _i(r["customer_id"]), "booking_type": r["booking_type"],
            "status": r["status"],
            "hotel_id": _i(r["hotel_id"], default=None), "room_id": _i(r["room_id"], default=None),
            "restaurant_id": _i(r["restaurant_id"], default=None),
            "table_id": _i(r["table_id"], default=None),
            "activity_id": _i(r["activity_id"], default=None),
            "init_day": _d(r["init_day"]), "end_day": _d(r["end_day"]),
            "hour": r["hour"] or None, "num_people": _i(r["num_people"]),
            "total_price": _f(r["total_price"]), "currency": r["currency"],
            "created_at": _dt(r["created_at"]), "created_by_ip": config.SEED_IP,
        })
    return out


def _index_by(items: list[dict], key: str) -> dict:
    return {item[key]: item for item in items}


def _group_by(items: list[dict], key: str) -> dict:
    groups: dict = {}
    for item in items:
        groups.setdefault(item[key], []).append(item)
    return groups


# ---------------------------------------------------------------------------
# Catalog (read-only, loaded once at startup)
# ---------------------------------------------------------------------------
class Catalog:
    def __init__(self, data_dir: Path):
        self.cities = _load_cities(data_dir / "cities.csv")
        self.hotels = _load_hotels(data_dir / "hotels.csv")
        self.room_types = _load_room_types(data_dir / "room_types.csv")
        self.rooms = _load_rooms(data_dir / "rooms.csv")
        self.restaurants = _load_restaurants(data_dir / "restaurants.csv")
        self.tables = _load_tables(data_dir / "restaurant_tables.csv")
        self.dishes = _load_dishes(data_dir / "dishes.csv")
        self.activities = _load_activities(data_dir / "activities.csv")
        self.customers = _load_customers(data_dir / "customers.csv")

        self.hotels_by_id = _index_by(self.hotels, "hotel_id")
        self.room_types_by_id = _index_by(self.room_types, "room_type_id")
        self.rooms_by_id = _index_by(self.rooms, "room_id")
        self.restaurants_by_id = _index_by(self.restaurants, "restaurant_id")
        self.tables_by_id = _index_by(self.tables, "table_id")
        self.dishes_by_id = _index_by(self.dishes, "dish_id")
        self.activities_by_id = _index_by(self.activities, "activity_id")
        self.customers_by_id = _index_by(self.customers, "customer_id")

        self.room_types_by_hotel = _group_by(self.room_types, "hotel_id")
        self.rooms_by_hotel = _group_by(self.rooms, "hotel_id")
        self.rooms_by_room_type = _group_by(self.rooms, "room_type_id")
        self.tables_by_restaurant = _group_by(self.tables, "restaurant_id")
        self.dishes_by_restaurant = _group_by(self.dishes, "restaurant_id")


# ---------------------------------------------------------------------------
# Bookings (seed + dynamic, with overlap / capacity checks)
# ---------------------------------------------------------------------------
class BookingConflict(Exception):
    """Raised when a requested booking would overlap with an existing one."""


class NotFound(Exception):
    """Raised when a referenced entity (room, table, activity, customer...) doesn't exist."""


class BookingStore:
    def __init__(self, catalog: Catalog, seed_bookings_path: Path):
        self.catalog = catalog
        self.seed_bookings = _load_seed_bookings(seed_bookings_path)
        self.dynamic_bookings = db.load_all_bookings()
        self.lock = threading.Lock()

        seed_max = max((b["booking_id"] for b in self.seed_bookings), default=0)
        dyn_max = max((b["booking_id"] for b in self.dynamic_bookings), default=0)
        self._next_booking_id = max(seed_max, dyn_max, db.max_booking_id()) + 1
        self._reference_counter = itertools.count(1)

        # Indices over the seed data (immutable after startup)
        self._seed_by_room = _group_by([b for b in self.seed_bookings if b["room_id"] is not None], "room_id")
        self._seed_by_table = _group_by([b for b in self.seed_bookings if b["table_id"] is not None], "table_id")
        self._seed_by_activity = _group_by(
            [b for b in self.seed_bookings if b["activity_id"] is not None], "activity_id"
        )

    # -- internal helpers ---------------------------------------------------
    def _dynamic_for_ip(self, ip: str) -> list[dict]:
        return [b for b in self.dynamic_bookings if b["created_by_ip"] == ip]

    def visible_bookings(self, requester_ip: str) -> list[dict]:
        """All bookings a given attendee (IP) is allowed to see: the shared
        seed dataset plus whatever they personally created."""
        return self.seed_bookings + self._dynamic_for_ip(requester_ip)

    def get_booking(self, booking_id: int, requester_ip: str) -> Optional[dict]:
        """Returns the booking only if it is visible to this requester."""
        for b in self.visible_bookings(requester_ip):
            if b["booking_id"] == booking_id:
                return b
        return None

    def _visible_for_room(self, room_id: int, requester_ip: str) -> list[dict]:
        seed = self._seed_by_room.get(room_id, [])
        own_dynamic = [b for b in self.dynamic_bookings
                       if b["room_id"] == room_id and b["created_by_ip"] == requester_ip]
        return seed + own_dynamic

    def _visible_for_table(self, table_id: int, requester_ip: str) -> list[dict]:
        seed = self._seed_by_table.get(table_id, [])
        own_dynamic = [b for b in self.dynamic_bookings
                       if b["table_id"] == table_id and b["created_by_ip"] == requester_ip]
        return seed + own_dynamic

    def _visible_for_activity(self, activity_id: int, requester_ip: str) -> list[dict]:
        seed = self._seed_by_activity.get(activity_id, [])
        own_dynamic = [b for b in self.dynamic_bookings
                       if b["activity_id"] == activity_id and b["created_by_ip"] == requester_ip]
        return seed + own_dynamic

    # -- availability checks -------------------------------------------------
    def room_conflicts(self, room_id: int, init_day: date, end_day: date, requester_ip: str) -> list[dict]:
        """Bookings that would conflict with [init_day, end_day) for this room."""
        conflicts = []
        for b in self._visible_for_room(room_id, requester_ip):
            if b["status"] not in BLOCKING_STATUSES:
                continue
            if init_day < b["end_day"] and end_day > b["init_day"]:
                conflicts.append(b)
        return conflicts

    def table_conflicts(self, table_id: int, day: date, hour: str, requester_ip: str) -> list[dict]:
        conflicts = []
        for b in self._visible_for_table(table_id, requester_ip):
            if b["status"] not in BLOCKING_STATUSES:
                continue
            if b["init_day"] == day and b["hour"] == hour:
                conflicts.append(b)
        return conflicts

    def activity_booked_count(self, activity_id: int, day: date, requester_ip: str) -> int:
        total = 0
        for b in self._visible_for_activity(activity_id, requester_ip):
            if b["status"] not in BLOCKING_STATUSES:
                continue
            if b["init_day"] == day:
                total += b["num_people"]
        return total

    # -- booking creation / deletion ----------------------------------------
    def create_booking(self, payload, requester_ip: str) -> dict:
        """
        `payload` is a validated `schemas.BookingCreateRequest`. Raises
        `NotFound` if a referenced entity doesn't exist, or `BookingConflict`
        if the requested slot is not available.
        """
        if payload.customer_id not in self.catalog.customers_by_id:
            raise NotFound(f"customer_id {payload.customer_id} does not exist")

        with self.lock:
            if payload.booking_type == "hotel_room":
                room = self.catalog.rooms_by_id.get(payload.room_id)
                if room is None:
                    raise NotFound(f"room_id {payload.room_id} does not exist")
                room_type = self.catalog.room_types_by_id.get(room["room_type_id"])
                max_capacity = (room_type["max_adults"] + room_type["max_children"]) if room_type else None
                if max_capacity is not None and payload.num_people > max_capacity:
                    raise BookingConflict(
                        f"room {payload.room_id} has a maximum capacity of {max_capacity} people"
                    )
                conflicts = self.room_conflicts(payload.room_id, payload.init_day, payload.end_day, requester_ip)
                if conflicts:
                    raise BookingConflict(
                        f"room {payload.room_id} is already booked for an overlapping date range "
                        f"(conflicting booking id(s): {[c['booking_id'] for c in conflicts]})"
                    )
                nights = (payload.end_day - payload.init_day).days
                total_price = round((room_type["base_price_per_night"] if room_type else 0) * nights, 2)
                hotel_id = room["hotel_id"]
                restaurant_id = table_id = activity_id = None

            elif payload.booking_type == "restaurant_table":
                table = self.catalog.tables_by_id.get(payload.table_id)
                if table is None:
                    raise NotFound(f"table_id {payload.table_id} does not exist")
                if payload.num_people > table["capacity"]:
                    raise BookingConflict(
                        f"table {payload.table_id} has a maximum capacity of {table['capacity']} people"
                    )
                conflicts = self.table_conflicts(payload.table_id, payload.init_day, payload.hour, requester_ip)
                if conflicts:
                    raise BookingConflict(
                        f"table {payload.table_id} is already booked on {payload.init_day} at "
                        f"{payload.hour} (conflicting booking id(s): {[c['booking_id'] for c in conflicts]})"
                    )
                restaurant = self.catalog.restaurants_by_id.get(table["restaurant_id"])
                price_per_person = {"budget": 15, "mid-range": 28, "upscale": 48, "luxury": 85}.get(
                    restaurant["price_range"] if restaurant else "mid-range", 28
                )
                total_price = round(price_per_person * payload.num_people, 2)
                restaurant_id = table["restaurant_id"]
                hotel_id = room_id = activity_id = None

            else:  # activity
                activity = self.catalog.activities_by_id.get(payload.activity_id)
                if activity is None:
                    raise NotFound(f"activity_id {payload.activity_id} does not exist")
                booked = self.activity_booked_count(payload.activity_id, payload.init_day, requester_ip)
                remaining = activity["max_capacity"] - booked
                if payload.num_people > remaining:
                    raise BookingConflict(
                        f"activity {payload.activity_id} only has {remaining} spot(s) left on "
                        f"{payload.init_day} (requested {payload.num_people})"
                    )
                total_price = round(activity["price"] * payload.num_people, 2)
                hotel_id = room_id = restaurant_id = table_id = None

            booking_id = self._next_booking_id
            self._next_booking_id += 1
            reference = f"BK{booking_id:06d}{next(self._reference_counter):02d}"

            booking = {
                "booking_id": booking_id,
                "booking_reference": reference,
                "customer_id": payload.customer_id,
                "booking_type": payload.booking_type,
                "status": "confirmed",
                "hotel_id": hotel_id if payload.booking_type == "hotel_room" else None,
                "room_id": payload.room_id if payload.booking_type == "hotel_room" else None,
                "restaurant_id": restaurant_id if payload.booking_type == "restaurant_table" else None,
                "table_id": payload.table_id if payload.booking_type == "restaurant_table" else None,
                "activity_id": payload.activity_id if payload.booking_type == "activity" else None,
                "init_day": payload.init_day,
                "end_day": payload.end_day,
                "hour": payload.hour,
                "num_people": payload.num_people,
                "total_price": total_price,
                "currency": "EUR",
                "created_at": datetime.now().replace(microsecond=0),
                "created_by_ip": requester_ip,
            }

            db.insert_booking(booking)
            self.dynamic_bookings.append(booking)
            return booking

    def delete_by_ip(self, requester_ip: str) -> int:
        with self.lock:
            deleted = db.delete_bookings_by_ip(requester_ip)
            self.dynamic_bookings = [b for b in self.dynamic_bookings if b["created_by_ip"] != requester_ip]
            return deleted
